# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20170930_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Код доступа'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='email',
            field=models.CharField(max_length=200, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='fio',
            field=models.CharField(max_length=200, verbose_name='Фамилия, имя, отчество'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Round', verbose_name='Раунд'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='round',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
