# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20170930_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='grade',
            field=models.IntegerField(default=6, max_length=2, verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
