# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_examiner_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='grade',
            field=models.IntegerField(verbose_name='Класс'),
        ),
    ]
