# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20170930_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Задача')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('grade', models.IntegerField(verbose_name='Класс')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Round', verbose_name='Раунд')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Subject', verbose_name='Предмет')),
            ],
        ),
    ]
