# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='ID участника')),
                ('value', models.IntegerField(verbose_name='Оценка')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время проверки')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Examiner', verbose_name='Экзаменатор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Task', verbose_name='Задача')),
            ],
        ),
    ]
